# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: stateoftheartio/qt6:6.3-mingw-aqt
    # - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            sudo apt-get update
            sudo apt install qt5-qmake -y
            sudo apt-get install qt5-default qtmultimedia5-dev build-essential -y
            git submodule update --init --recursive
            qmake -spec linux-g++ CONFIG+=debug -o ../build/Makefile
            cd UnitTests
            qmake -spec linux-g++ CONFIG+=debug -o ../../UnitTestBuild/Makefile
            cd ../../build 
            make clean 
            make qmake_all 
            make all -j

            cd ../UnitTestBuild 
            make clean 
            make qmake_all 
            make all -j     

      # start UnitTests
      - run:            
            cd Test_Database/
            ./Test_Database >> testResults

      
      - store_artifacts: 
         path: testResults
         destination: unitTestResults


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  buildProject-workflow:
    jobs:
      - build-and-test
